research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

newsletter_writer_task:
  description: >
    Write a newsletter about {topic} based on the research findings
    Make sure to include engaging content and insightful analysis.
  expected_output: >
    A well-structured newsletter about the {topic} with a catchy title, introduction,
    main content, and conclusion.
  agent: newsletter_writer

newsletter_editor_task:
  description: >
    Edit the newsletter article about {topic} to ensure quality and consistency
  expected_output: >
    A newsletter article about {topic} that meets the highest standards of quality.
  agent: newsletter_editor
